changed load_test_data to use GitPython
roocs/roocs-utils pull request #56
Opened 2021-02-17 14:39 UTC by jhaigh0

Now cloning the `mini-esgf-data` repository with GitPython instead of making an os command call. This makes pulling the repo, to keep it up to date, simpler.

2021-02-17 15:06 UTC, agstephens requested changes
@jhaigh0: This is a great start. I've realised there is another thing to consider:
- We might not always want to use `master`.

The implications are:

1. It would be good to generalise the `load_test_data()` function to include two inputs:
 - repo_url=TEST_DATA_REPO_URL
 - branch="master"

2. And then you'll need to do some more investigation of `GitPython` so that you make sure the correct `branch` is:
 - checked out after the `clone_from` 
 - switched to for the `pull`

Thanks

2021-02-17 15:10 UTC, agstephens commented
@jhaigh0 Also, the following file needs updating to use the `requirements_dev.txt` file:
```
https://github.com/roocs/roocs-utils/blob/master/.github/workflows/main.yml#L22
```
Add an extra line for the dev requirements file:
```
        if [ -f requirements_dev.txt ]; then pip install -r requirements_dev.txt; fi
```

2021-02-17 20:07 UTC, agstephens approved these changes

2021-02-17 20:10 UTC, agstephens commented
@ellesmith88 Please can you do a quick review to confirm that you are happy with this PR. I think it looks good.

2021-02-18 09:36 UTC, ellesmith88 approved these changes
I think this looks really good!

2021-02-18 11:51 UTC, merged